// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace OlxDataAccess.Models
{
    [Table("Chat_Message")]
    public partial class Chat_Message
    {
        [Key]
        public int Id { get; set; }
        public int Chat_Id { get; set; }
        public int Sender_Id { get; set; }
        public string Message { get; set; }
        public string Image { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Send_Date { get; set; }

        [ForeignKey("Chat_Id")]
        [InverseProperty("Chat_Messages")]
        public virtual Chat Chat { get; set; }
        [ForeignKey("Sender_Id")]
        [InverseProperty("Chat_Messages")]
        public virtual User Sender { get; set; }
    }
}