// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace OlxDataAccess.Models
{
    [Table("Favorite")]
    public partial class Favorite
    {
        [Key]
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Post_Id { get; set; }

        [ForeignKey("Post_Id")]
        [InverseProperty("Favorites")]
        public virtual Post Post { get; set; }
        [ForeignKey("User_Id")]
        [InverseProperty("Favorites")]
        public virtual User User { get; set; }
    }
}