// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace OlxDataAccess.Models
{
    [Table("Field")]
    public partial class Field
    {
        public Field()
        {
            Choices = new HashSet<Choice>();
            InverseParent = new HashSet<Field>();
        }

        [Key]
        public int Id { get; set; }
        public int Cat_Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Label { get; set; }
        [Required]
        [StringLength(50)]
        public string Label_Ar { get; set; }
        [Required]
        [StringLength(50)]
        public string Value_Type { get; set; }
        [Required]
        [StringLength(50)]
        public string Choice_Type { get; set; }
        public int? Max_Length { get; set; }
        public int? Min_Length { get; set; }
        public int? Max_Value { get; set; }
        public int? Min_Value { get; set; }
        public bool Is_Required { get; set; }
        public int? Parent_Id { get; set; }

        [ForeignKey("Cat_Id")]
        [InverseProperty("Fields")]
        public virtual Category Cat { get; set; }
        [ForeignKey("Parent_Id")]
        [InverseProperty("InverseParent")]
        public virtual Field Parent { get; set; }
        [InverseProperty("Field")]
        public virtual ICollection<Choice> Choices { get; set; }
        [InverseProperty("Parent")]
        public virtual ICollection<Field> InverseParent { get; set; }
    }
}