// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace OlxDataAccess.Models
{
    [Keyless]
    [Table("Field_Role")]
    public partial class Field_Role
    {
        public int Field_Id { get; set; }
        public bool Filterable { get; set; }
        public bool Included_In_Breadcrumbs { get; set; }
        public bool Included_In_Pathname { get; set; }
        public bool Included_In_Sitemap { get; set; }
        public bool Included_In_Title { get; set; }
        public bool Searchable { get; set; }

        [ForeignKey("Field_Id")]
        public virtual Field Field { get; set; }
    }
}