// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace OlxDataAccess.Models
{
    public partial class Governorate
    {
        public Governorate()
        {
            Cities = new HashSet<City>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Governorate_Name_Ar { get; set; }
        [Required]
        [StringLength(50)]
        public string Governorate_Name_En { get; set; }

        [InverseProperty("Governorate")]
        public virtual ICollection<City> Cities { get; set; }
    }
}