// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace OlxDataAccess.Models
{
    [Table("Post")]
    public partial class Post
    {
        public Post()
        {
            Favorites = new HashSet<Favorite>();
            Post_Images = new HashSet<Post_Image>();
        }

        [Key]
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Cat_Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Column(TypeName = "money")]
        public decimal Price { get; set; }
        public int? Price_Type { get; set; }
        public int Contact_Method { get; set; }
        public int? Post_Location { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Created_Date { get; set; }
        [Required]
        public bool? Is_Visible { get; set; }
        public int Views { get; set; }
        public bool Is_Special { get; set; }
        [Required]
        public string Fields { get; set; }

        [ForeignKey("Cat_Id")]
        [InverseProperty("Posts")]
        public virtual Category Cat { get; set; }
        [ForeignKey("Post_Location")]
        [InverseProperty("Posts")]
        public virtual City Post_LocationNavigation { get; set; }
        [ForeignKey("User_Id")]
        [InverseProperty("Posts")]
        public virtual User User { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        [InverseProperty("Post")]
        public virtual ICollection<Post_Image> Post_Images { get; set; }
    }
}